### ISSUE TITLE
Put completion of training video in Session 10 only

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-project-multilingual#52]
SESSION 9
Not sure if it makes sense to have the Completion of Training video in this session. I know we’ve discussed this, but I think the features it highlight is really more appropriate in Session 10 - especially if it comes after taking some time off between 9 and 10. Looks like this video is already in 10-6. I’d think about just leaving it there.

**Comment by ChrisChasm** [comment]
This was a suggestion from testing. Can we have a discussion about it?

**Comment by ChrisChasm** [comment]
done

**Comment by himayrunner** [comment]
Sorry I missed this discussion. I assume you just went ahead and put the completion of training in session 10-6?
